// <auto-generated />
using GeoImageService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoImageService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260329173034_AddTimestamps")]
    partial class AddTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoImageService.Application.Models.Images.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("GeoTiffFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geo_tiff_file_path");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("GeoImageService.Application.Models.Images.Image", b =>
                {
                    b.OwnsOne("GeoImageService.Application.Models.Images.CornersCoordinates", "CornersCoordinates", b1 =>
                        {
                            b1.Property<long>("ImageId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.HasKey("ImageId");

                            b1.ToTable("images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");

                            b1.OwnsOne("GeoImageService.Application.Models.Images.Coordinate", "BottomLeft", b2 =>
                                {
                                    b2.Property<long>("CornersCoordinatesImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_bottom_left_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_bottom_left_longitude");

                                    b2.HasKey("CornersCoordinatesImageId");

                                    b2.ToTable("images");

                                    b2.WithOwner()
                                        .HasForeignKey("CornersCoordinatesImageId")
                                        .HasConstraintName("fk_images_images_id");
                                });

                            b1.OwnsOne("GeoImageService.Application.Models.Images.Coordinate", "BottomRight", b2 =>
                                {
                                    b2.Property<long>("CornersCoordinatesImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_bottom_right_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_bottom_right_longitude");

                                    b2.HasKey("CornersCoordinatesImageId");

                                    b2.ToTable("images");

                                    b2.WithOwner()
                                        .HasForeignKey("CornersCoordinatesImageId")
                                        .HasConstraintName("fk_images_images_id");
                                });

                            b1.OwnsOne("GeoImageService.Application.Models.Images.Coordinate", "TopLeft", b2 =>
                                {
                                    b2.Property<long>("CornersCoordinatesImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_top_left_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_top_left_longitude");

                                    b2.HasKey("CornersCoordinatesImageId");

                                    b2.ToTable("images");

                                    b2.WithOwner()
                                        .HasForeignKey("CornersCoordinatesImageId")
                                        .HasConstraintName("fk_images_images_id");
                                });

                            b1.OwnsOne("GeoImageService.Application.Models.Images.Coordinate", "TopRight", b2 =>
                                {
                                    b2.Property<long>("CornersCoordinatesImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_top_right_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("corners_coordinates_top_right_longitude");

                                    b2.HasKey("CornersCoordinatesImageId");

                                    b2.ToTable("images");

                                    b2.WithOwner()
                                        .HasForeignKey("CornersCoordinatesImageId")
                                        .HasConstraintName("fk_images_images_id");
                                });

                            b1.Navigation("BottomLeft")
                                .IsRequired();

                            b1.Navigation("BottomRight")
                                .IsRequired();

                            b1.Navigation("TopLeft")
                                .IsRequired();

                            b1.Navigation("TopRight")
                                .IsRequired();
                        });

                    b.OwnsOne("GeoImageService.Application.Models.Images.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<long>("ImageId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<double?>("End")
                                .HasColumnType("double precision")
                                .HasColumnName("time_stamps_end");

                            b1.Property<double?>("Start")
                                .HasColumnType("double precision")
                                .HasColumnName("time_stamps_start");

                            b1.HasKey("ImageId");

                            b1.ToTable("images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId")
                                .HasConstraintName("fk_images_images_id");
                        });

                    b.Navigation("CornersCoordinates")
                        .IsRequired();

                    b.Navigation("TimeStamps")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
